# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('header', models.CharField(default='Unknown', max_length=200)),
                ('hardcoded', models.BooleanField(default=True)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_medium', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
