# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170716_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='header',
            field=models.CharField(max_length=200),
        ),
    ]
