# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 22:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20170716_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
