# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('header', models.CharField(default='Unknown', max_length=200)),
                ('in_menu', models.BooleanField(default=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('menu_title', models.CharField(default='Unknown', max_length=200)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
