# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 23:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
