# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 05:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
