# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170705_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='header',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
