# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_webpage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='menu_order',
            field=models.IntegerField(default=0),
        ),
    ]
