# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170712_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='menu_title',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
