# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('header', models.CharField(default='Unknown', max_length=200)),
                ('in_menu', models.BooleanField(default=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('menu_title', models.CharField(default='Unknown', max_length=200)),
                ('hardcoded', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('abstract', tinymce.models.HTMLField(blank=True)),
                ('quote', tinymce.models.HTMLField(blank=True)),
                ('file', models.FileField(upload_to='texts')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='texts.Category')),
            ],
        ),
    ]
