# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
