# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_text_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='published_at',
            field=models.DateField(),
        ),
    ]
